# Notebook for experimenting and learning

In [2]:
# understanding torch.transpose()
import torch

A = torch.randn(1, 3, 4)
B = torch.randn(1, 3, 4)

print(A)
print(B)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.5 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/rcss/Documents/master/math-reasoning/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/rcss/Documents/master/math-reasoning/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/rcss/Documents/master/math-reasoning/.venv/lib/python3.12/site-packages/ipykern

tensor([[[-0.5826,  2.5874,  0.9559,  0.9259],
         [ 0.1693, -0.4877,  0.6334,  1.2879],
         [-0.1584, -0.2066, -0.7949,  1.7970]]])
tensor([[[ 0.4281, -0.7625, -0.9006,  0.0649],
         [-0.7586,  0.3312, -0.7936,  0.9443],
         [-0.5790, -1.2730,  1.3174,  0.7216]]])


In [16]:
print(A.shape)

torch.Size([1, 3, 4])


In [11]:
# trying to multiply these
# The main difference lies in robustness:
# First case: transposes first dim, transposes 2nd dim
# Second case: GENERAL -> Will ALWAYS transpose the last two dims
# Third case: Same thing as first. Swapping dims change nothing
C = A @ B.transpose(dim0=1, dim1=2)
D = A @ B.transpose(dim0=-2, dim1=-1)
E = A @ B.transpose(dim0=2, dim1=1)

print(C) 
print(D)
print(E)


tensor([[[-1.1571,  1.0569, -2.6868],
         [ 2.2595, -4.0820, -0.8928],
         [ 1.1520, -0.8884,  0.9871]]])
tensor([[[-1.1571,  1.0569, -2.6868],
         [ 2.2595, -4.0820, -0.8928],
         [ 1.1520, -0.8884,  0.9871]]])
tensor([[[-1.1571,  1.0569, -2.6868],
         [ 2.2595, -4.0820, -0.8928],
         [ 1.1520, -0.8884,  0.9871]]])


In [17]:
print(D.shape)

torch.Size([1, 3, 3])


In [19]:
Z = D @ A
print(Z)
print(Z.shape)

tensor([[[   -inf,     nan,     nan,     nan],
         [   -inf,     inf,     inf,     inf],
         [-1.2432, -0.2798, -0.4479,  0.8259]]])
torch.Size([1, 3, 4])


In [15]:
# torch.tril()
B, T, C = A.shape
# 1. First, create a T x T tensor of ones
tril = torch.ones(T, T).tril()
D = D.masked_fill(tril == 0, float("-inf"))

D

tensor([[[-1.1571,    -inf,    -inf],
         [ 2.2595, -4.0820,    -inf],
         [ 1.1520, -0.8884,  0.9871]]])

In [ ]:
# Understanding view
# torch.Tensor.view(-1) is a method in PyTorch that reshapes a tensor into a one-dimensional (1D) tensor \ 
# while automatically inferring the total number of elements. 
A = torch.randn(1, 2, 3)
A.view(-1)
A

tensor([[[-0.0019, -0.6673, -0.0354],
         [ 0.9114,  1.0840,  0.1493]]])

In [9]:
torch.arange(30)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
import torch.nn.functional as F

print(A)
print(F.softmax(A, dim=1))

tensor([[[-0.0019, -0.6673, -0.0354],
         [ 0.9114,  1.0840,  0.1493]]])
tensor([[[0.2863, 0.1479, 0.4540],
         [0.7137, 0.8521, 0.5460]]])


In [ ]:
A = torch.randn(3, 4, 8)
B, T, C = A.shape
targets = torch.randn(C)

print(A)
print(targets)

tensor([[[-1.1960e+00, -9.2397e-01, -1.4849e+00,  3.3303e-01,  1.2404e+00,
          -2.3118e-02,  4.8440e-01, -3.6899e-03],
         [-1.4782e+00,  2.7797e-01,  1.2126e+00,  1.4664e-01, -1.2690e+00,
           4.1717e-02, -7.7940e-01,  1.6522e-02],
         [-1.9880e-01, -2.2401e+00, -2.0038e-01,  7.5429e-03, -5.8926e-01,
           1.9760e+00,  8.8920e-01,  4.8405e-01],
         [ 7.7628e-01, -7.2850e-01, -2.5311e-01,  9.6201e-01,  1.1002e+00,
           1.0281e+00, -3.3578e-01, -2.2344e-01]],

        [[ 3.8714e-01,  1.8066e-01, -4.3854e-01, -1.5099e-03,  4.6349e-01,
          -5.3799e-01, -1.3896e+00,  8.4757e-01],
         [-3.4223e-01,  6.0040e-01, -5.8346e-01,  4.3064e-01, -3.6337e-01,
          -1.8906e-01, -1.2512e-01, -1.3155e+00],
         [ 1.5843e+00,  6.1823e-01, -8.0553e-01,  1.4131e+00,  1.4843e+00,
          -9.7982e-01, -1.5598e+00, -8.4395e-01],
         [ 7.6705e-02,  6.2949e-01, -1.7250e+00, -3.6316e-01, -5.5973e-01,
           3.6524e-01,  5.6556e-01,  1.6448e+00]

In [15]:
B = A.view(B*T, C)
B

tensor([[-1.1960e+00, -9.2397e-01, -1.4849e+00,  3.3303e-01,  1.2404e+00,
         -2.3118e-02,  4.8440e-01, -3.6899e-03],
        [-1.4782e+00,  2.7797e-01,  1.2126e+00,  1.4664e-01, -1.2690e+00,
          4.1717e-02, -7.7940e-01,  1.6522e-02],
        [-1.9880e-01, -2.2401e+00, -2.0038e-01,  7.5429e-03, -5.8926e-01,
          1.9760e+00,  8.8920e-01,  4.8405e-01],
        [ 7.7628e-01, -7.2850e-01, -2.5311e-01,  9.6201e-01,  1.1002e+00,
          1.0281e+00, -3.3578e-01, -2.2344e-01],
        [ 3.8714e-01,  1.8066e-01, -4.3854e-01, -1.5099e-03,  4.6349e-01,
         -5.3799e-01, -1.3896e+00,  8.4757e-01],
        [-3.4223e-01,  6.0040e-01, -5.8346e-01,  4.3064e-01, -3.6337e-01,
         -1.8906e-01, -1.2512e-01, -1.3155e+00],
        [ 1.5843e+00,  6.1823e-01, -8.0553e-01,  1.4131e+00,  1.4843e+00,
         -9.7982e-01, -1.5598e+00, -8.4395e-01],
        [ 7.6705e-02,  6.2949e-01, -1.7250e+00, -3.6316e-01, -5.5973e-01,
          3.6524e-01,  5.6556e-01,  1.6448e+00],
        [ 7.0882

In [21]:
A = torch.randn(2, 4)
print(A)
A = A[:, -3:]
A

tensor([[ 1.2154, -0.2132, -0.9319,  0.1608],
        [-0.3415,  0.2698,  0.6019, -1.1824]])


tensor([[-0.2132, -0.9319,  0.1608],
        [ 0.2698,  0.6019, -1.1824]])

In [8]:
import torch

torch.arange(0, 16, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [3]:
import torch
from einops import rearrange

idx = torch.randn([1, 16])
head_size = 16

def precompute_freqs_cis(idx, theta: int=10000):
    """Implements the Rotary Position Embedding (RoPE)
    For this specific implementation of RoPE, I followed the instructions 
    presented in this video: http://youtube.com/watch?v=V8r__fXx7tU

    There is actually a twist in this implementation when compared to the video: Hugging Face
    
    Args:
        idx: input tokens (B, T)
        theta: this is a hyperparameter. In both implementations, Vaswani et al. [2017] and
        RoPE, authors use it as 10000. Theta controls how fast the pairs of tokens will rotate. A bigger theta
        makes it rotate slower, a smaller theta, make them rotate faster.
    """
    # assert that the Embedding Dimension is divisible by two. The original implementation extrapolates
    # the 2D case for rotation and actually rotates each component of the embedding in blocks of 2. They
    # do not add much of an explanation, nor does the video. The video explains the Reasons for this, not 
    # the intuition:
    # 1. Efficient & fast 
    # 2. Parameter free (in 3D there a much more ways you can rotate something and you can actually "learn" this as well)
    # 3. Interpretable
    # 4. Tests made, trying to learn hiugher order rotation, does not bring any gains.
    assert head_size % 2 == 0

    # For the actual implementation, what we are going to do here is: We'll use the angular frequency formula 
    # in order to calculate HOW MUCH each term must rotate. Formula is given by: w_k = 1/theta^{2k/d}, where 
    # - w_k is the angular frequency
    # - d is the head_size
    # - k is the index of the pair we are selecting, where k in [0, d/2-1]
    freqs = 1 / (theta**(torch.arange(0, head_size, 2, dtype=torch.float32) / head_size)) # (d/2)

    # calculating the actual rotation for each position. Equivalent to m x \theta
    _, T = idx.shape
    t = torch.arange(0, T) # (T)
    freqs = torch.outer(t, freqs) # (T, d/2)

    # defining the rotation matrix
    cos = torch.cos(freqs)
    sin = torch.sin(freqs)
    out = torch.stack([cos, -sin, sin, cos], dim=-1) # (T, d/2, 4)
    out = rearrange(out, "t d_half (i j)->t d_half i j", i=2, j=2) # (T, d/2, 2, 2)

    return out.float()

In [6]:
o = precompute_freqs_cis(idx)
o


tensor([[[[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]],

         [[ 1.0000e+00, -0.0000e+00],
          [ 0.0000e+00,  1.0000e+00]]],


        [[[ 5.4030e-01, -8.4147e-01],
          [ 8.4147e-01,  5.4030e-01]],

         [[ 9.5042e-01, -3.1098e-01],
          [ 3.1098e-01,  9.5042e-01]],

         [[ 9.9500e-01, -9.9833e-02],
          [ 9.9833e-02,  9.9500e-01]],

         [[ 9.9950e-01, -3.1618e-02],
          [ 3.1618e-02,  9.9950e-01]],

         [[ 9.9995e-01, -9.9998e-03],
          [ 9.9998e-03, 

In [16]:
x = torch.randn([1, 4, 8]) 

def rotate_half(x):
    """Implementing the computational efficient realization of rotary matrix multiplication

    This shows on original paper (https://arxiv.org/pdf/2104.09864), section 3.4.2
    """
    print(x)
    x1 = x[..., 0::2] # Even indices  
    x2 = x[..., 1::2] # Odd indices
    print(x1)
    print(x2)
    out = torch.stack([-x2, x1], dim=-1)
    print(out)
    print(out.shape)
    print(out.flatten(-2).shape)

rotate_half(x)

tensor([[[ 0.1605, -0.8035,  0.3676, -0.8588,  0.4623,  0.5716, -0.8919,
          -1.1363],
         [-1.6599,  2.0039, -1.1203, -1.9387, -0.0575, -0.7804,  0.2311,
          -0.4883],
         [ 0.4951,  1.0204,  0.2573,  1.3324,  0.1823, -1.2259, -0.8071,
          -1.1899],
         [ 0.0723, -0.1151, -1.1004, -0.7286, -1.0514, -0.0583,  0.6615,
          -0.5613]]])
tensor([[[ 0.1605,  0.3676,  0.4623, -0.8919],
         [-1.6599, -1.1203, -0.0575,  0.2311],
         [ 0.4951,  0.2573,  0.1823, -0.8071],
         [ 0.0723, -1.1004, -1.0514,  0.6615]]])
tensor([[[-0.8035, -0.8588,  0.5716, -1.1363],
         [ 2.0039, -1.9387, -0.7804, -0.4883],
         [ 1.0204,  1.3324, -1.2259, -1.1899],
         [-0.1151, -0.7286, -0.0583, -0.5613]]])
tensor([[[[ 0.8035,  0.1605],
          [ 0.8588,  0.3676],
          [-0.5716,  0.4623],
          [ 1.1363, -0.8919]],

         [[-2.0039, -1.6599],
          [ 1.9387, -1.1203],
          [ 0.7804, -0.0575],
          [ 0.4883,  0.2311]],

  